# https://docs.blender.org/manual/en/dev/advanced/extensions/index.html
schema_version = "1.0.0"
id = "gob"
name = "GoB"
version = "4.1.1"
tagline = "GoB providing a bridge between ZBrush and Blender"
maintainer = "Daniel Grauer (kromar)"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/JoseConseco/GoB/wiki"
copyright = ["2024 Jose Conseco", "2024 Daniel Grauer (kromar)"]
platforms = ["windows-x64", "macos-arm64"]
[permissions]
  files = "Requires access to deploy Zbrush configuration files, export models and send them to Zbrush"
[build] 
  paths_exclude_pattern = ["/.git/", "__pycache__/"]
