schema_version = "1.0.0"

id = "gob"
version = "4.0.4"
name = "GoB"
tagline = "An unofficial GOZ-like addon for Blender"
maintainer = "Daniel Grauer (kromar)"
type = "add-on"

# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

website = "https://github.com/JoseConseco/GoB/wiki"


copyright = [
"2024 Daniel Grauer (kromar)",
"2024 Jose Conseco",
]

platforms = ["windows-x64", "macos-arm64"]

[permissions]
files = "Requires access to deploy Zbrush configuration files"

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
]
